### ISSUE TITLE
Link a device option doesn’t work on desktop

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-ios#457] opened 2021-07-12 03:05 UTC
When you scan the QR code with your phone it just loads endlessly. Never connects/links.

iPhone 12 Pro
iOS 14.6
Session 1.11.6

**Comment by Snocember** [comment] 2021-07-14 14:43
Could not reproduce. It linked after 2 seconds.

Device: iPhone 6s+
OS: iOS 14.6
Version of Session: 1.11.8 (262)

**Comment by RyanRory** [comment] 2021-08-31 01:17
It seems like this is not an issue anymore. I'll just closed this.

**Closed by RyanRory** 2021-08-31 01:17 UTC
