### ISSUE TITLE
Session finds a path and delivers messages on airplane mode

### ISSUE THREAD

**Issue by MahdiNazemi** [oxen-io/session-ios#717] opened 2022-10-22 17:24 UTC
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

1. When I open Session in Airplane Mode, I see a green dot next to Path and find that Session has been able to establish a path to the destination. Completely closing the app and reopening it does not resolve the issue. The expected behavior is to see a yellow (or maybe red) dot next to Path and no established paths.
2. Sending a message in Airplane mode and with a path established as described in 1. is successful, and a delivery indicator (i.e., a single check mark) is shown below the message.

**Smartphone:**

 - Device: iPhone XS, iPhone 14 Pro Max
 - OS: iOS 16.0.3
 - Session Version: 2.2.0

**Additional context**

I have been trying to use Session with my family members in the past few months, but it looks like Session is somehow censored where they live. Given the unrest in Iran in the past few weeks and [the Session's episode on censorship](https://www.youtube.com/watch?v=2q-7cdXtdbg), I thought I would see how Session manages to find a way to connect to a service node when it is censored. That is when I faced the aforesaid bug.

**Comment by fracting** [comment] 2022-10-24 02:42
I can reproduce it. Session should report a message delivery failure status, but it incorrectly shows a successful status.
(The receiver didn't receive any message of course)

**Comment by GittyUpMyHorsey** [comment] 2023-02-04 23:52
I can also reproduce this on the latest ios and session version.

**Comment by mpretty-cyro** [comment] 2023-02-06 01:59
I've included a couple of fixes in #777 for this:
- Updated the path status to take network reachability into account when displaying it's status
- Updated messages to correctly update their delivery/read status while the conversation screen is open

But I wasn't actually able to reproduce the issue where messages were still sending myself - one thing to double check is whether the wifi on the device was still enabled (when enabling airplane mode iOS doesn't actually disable wifi)

Feel free to reopen this once 2.2.6 becomes available if you still run into this issue

**Comment by RyanRory** [comment] 2023-02-07 23:25
Hi @fracting @MahdiNazemi, I'll close this for now since 2.2.6 is out. If you still have this issue, feel free to reopen this. Thanks!

**Comment by fracting** [comment] 2023-02-08 00:00
@RyanRory latest Session iOS version in App Store is 2.2.6

However, the latest version in https://github.com/oxen-io/session-ios/releases is 2.2.5

Did I miss anything?

I tested 2.2.6 from Session iOS but the message delivery status is still incorrect.

**Comment by fracting** [comment] 2023-02-08 00:01
Is there a button to reopen an issue? I can't find one.

**Comment by RyanRory** [comment] 2023-02-08 00:04
Hi @fracting , 2.2.6 is available on Github now. And I just reopened this issue.

**Comment by fracting** [comment] 2023-02-08 00:13
Sorry, my way of testing was incomplete, let me update my new test report:

After turning off the network:
(1) Sending to "Note to Self" still success.
(2) Sending to anyone else fails as expected.

Not sure what is the desired behavior for the edge case (1)?

**Comment by fracting** [comment] 2023-02-08 00:20
<img width="300" src="https://user-images.githubusercontent.com/194342/217396516-33f80380-14a0-4e72-8c11-9cad2cfe5337.png" />


BTW, with airplane mode, the onion routing path page does not update to something like "disconnected", do you want a separate report?

**Comment by mpretty-cyro** [comment] 2023-02-10 06:40
> Sorry, my way of testing was incomplete, let me update my new test report:
> 
> After turning off the network: (1) Sending to "Note to Self" still incorrectly report a success status. (2) Sending to anyone else fails as expected.
> 
> Not sure what is the desired behavior for the edge case (1)?

Looks like there was a bug in iOS where messages to 'Note to Self' weren't actually getting sent to the swarm - this has been fixed in #784 

> BTW, with airplane mode, the onion routing path page does not update to something like "disconnected", do you want a separate report?

I've updated these to turn red based on the device reachability as an interim solution (the path will still display because it gets cached); we are going to need to overhaul this screen once we look at doing Lokinet integration anyway as the path management is more complex

**Comment by mpretty-cyro** [comment] 2024-04-08 23:28
Closing this as #784 has been released for a while - if you are still experiencing this issue feel free to let us know and we can reopen it again

**Closed by mpretty-cyro** 2024-04-08 23:28 UTC
Labels: bug
