### ISSUE TITLE
No push messages with Session 1.11.22

### ISSUE THREAD

**Issue by glomeg132** [oxen-io/session-ios#591] opened 2022-03-20 06:52 UTC
Code of conduct

   

- [x]  I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

Describe the bug

I get no push messages after updating to the newest version of Session 1.11.22 on iOS 15.4. This error occurs on several iOS devices with newest iOS.

To reproduce

Send a message to another 15.4 iOS device and use Session 1.11.22.

Screenshots or logs

n/a

Smartphone (please complete the following information):

    Device: iPhone 12 pro
    OS: iOS 15.4
    Version of Session or latest commit hash: 1.11.22

Additional context

n/a

**Comment by ciugam** [comment] 2022-03-20 14:02
Hi, 
I have the same problem, same iOS 15.4 and Session 1.11.22, my device is iPhone XS.

**Comment by dsincl12** [comment] 2022-03-20 14:18
Yes seems to affect all iOS users. Quite hard to try to push for Session with friends and family when stuff like this happens. Really hoping for a quick release fix.

**Comment by dsincl12** [comment] 2022-03-20 14:26
We turned off "Fast mode" under notifications to see if it had any effect. That didn't work either unfortunately.

**Comment by ciugam** [comment] 2022-03-20 14:29
I've noticed that also in-app messages are not updated, I can confirm this because on my desktop app the notification is working properly and I have latest messages. 
I hope in a quick fix, like you said.

**Comment by RyanRory** [comment] 2022-03-20 23:02
Hi guys, thanks for your feedback, we've been aware of this issue and we'll make a quick fix for this. Cheers!

**Comment by RyanRory** [comment] 2022-03-24 00:22
Hi guys, happy to report the push notification is fixed in our latest release 1.11.23! :)

**Closed by RyanRory** 2022-03-24 00:22 UTC
Labels: bug
