### ISSUE TITLE
Chat history in open groups - huge amount of blank space

### ISSUE THREAD

**Issue by BeHooman** [oxen-io/session-ios#644] opened 2022-07-14 11:07 UTC
- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
In open groups, at the end of every message there is a huge blank space, as if the the sender pressed the space bar thousands of times.

### Steps to reproduce
- tap on (any) open group
- every message is affected as aforementioned

#### Actual result:
A few messages occupy the entire screen because of this blank spaces

#### Expected result:
There shouldn’t be blank spaces at the end of messages, unless people actually pressed the spacebar.

### Screenshots
![3EBA7ACB-9D89-4266-A8D0-ECB2E77C17D3](https://user-images.githubusercontent.com/109044644/178969021-3605cdf6-699a-4b2a-a0cb-534a69599d0a.png)

### Device info
**Device**: iPad 9th gen
**iOS version**: 16
**Session version:** 1.13.0 (348)

**Comment by RyanRory** [comment] 2022-07-20 03:24
Hi @BeHooman thanks for the report, we are working on fixing this issue. Will keep you updated once the issue is fixed. Cheers!

**Comment by BeHooman** [comment] 2022-08-11 20:56
Good to know.
Still no fix in version 2.0.

**Comment by RyanRory** [comment] 2022-11-21 00:11
Hi @BeHooman, this issue should be fixed with our latest release. Thanks for the report, I'll close this issue now.

**Closed by RyanRory** 2022-11-21 00:11 UTC
Labels: bug
