### ISSUE TITLE
Some options are not saved when exiting configuration screens

### ISSUE THREAD

**Issue by smss2022** [oxen-io/session-ios#716] opened 2022-10-22 15:12 UTC
**Describe the bug**
Some options are not saved when exiting configuration screens.

**To reproduce**
1. Settings > Notifications > Activate "Sound when app is open" by moving the slider to the right;
2. Tap the Back arrow, exiting the previous screen and returning to Settings;
3. Tap Notifications again: the slider is back to the left, "Sound when app is open" remains deactivated.

1. Settings > Privacy > Activate "Read receipts" by moving the slider to the right;
2. Tap the Back arrow, exiting the previous screen and returning to Settings;
3. Tap Privacy again: the slider is back to the left, "Read receipts" remains deactivated.

**Smartphone (please complete the following information):**

 - Device: iPhone 13
 - OS: 16
 - Version of Session: 2.2.0

**Additional context**
The previous version was working as intended.

**Comment by smss2022** [comment] 2022-10-22 16:04
In a similar vein: once activated by moving their sliders to the right, the following options can no longer be deactivated:

-Lock Session (require Touch ID, Face ID or your passcode to unlock Session);
-Send Link Previews.

Move their respective sliders back to the left, exit and reenter the Privacy screen: the slider have returned to the right, in their On position

**Comment by MahdiNazemi** [comment] 2022-10-22 17:08
I am experiencing the same issue with the Lock Session and Read Receipts.
When I enable Lock Session, I am not even asked for permission to allow Session use Face ID.

Similarly, I cannot turn off Voice and Video Calls.

Session version: 2.2.0

**Comment by KeeJef** [comment] 2022-12-14 06:00
Since this issue was filed we overhauled the settings screen for Session, i can't seem to reproduce this issue on the new version, so i'm closing this for now, please reopen if the issue remains for you

**Closed by KeeJef** 2022-12-14 06:00 UTC
Labels: bug
