### ISSUE TITLE
Audio record button sticks

### ISSUE THREAD

**Issue by phsjr1** [oxen-io/session-ios#759] opened 2022-12-20 17:40 UTC
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When holding down the record button for long recordings, it often 'sticks' and you can't stop the recording...
You have to force quiet the app to get it to stop recording. 

### iOS Version

iOS 15.6

### Session Version

1.10.4

**Comment by RyanRory** [comment] 2023-01-11 22:58
Hi @phsjr1, thanks for the report. I noticed that you are on version 1.10.4, and the latest version is 2.2.4. Session has been improved a lot. Could you please update to the latest version and see if the issue is still there?

**Comment by phsjr1** [comment] 2023-01-11 23:20
THANKS

------- Original Message -------

**Comment by KeeJef** [comment] 2023-02-08 03:33
Assuming that this has been fixed, closing for now

**Closed by KeeJef** 2023-02-08 03:33 UTC
Labels: bug
