### ISSUE TITLE
[BUG] <title>Unable to send pictures and links

### ISSUE THREAD

**Issue by miumiu099** [oxen-io/session-ios#809] opened 2023-04-02 04:24 UTC
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently unable to send pictures and links on Session, but sending words is ok.
The same issue goes with desktop too,
Also,  your website has trouble showing pictures, thought you should know.
Please take a look when you have time, thank you.

**Comment by fracting** [comment] 2023-04-02 05:53
Hi, thanks for the report.

Are you unable to send pictures and links to an Open Group (Community), or are you unable to send picture and links to your contact in DM?

The official Communities (Session / Oxen / Lokient) has disabled attachments, which means you can't sent pictures, and you can't send links with preview, but you can send links without preview.

**Comment by dmastrorillo** [comment] 2023-04-02 10:45
Hi @fracting 

Facing this too. Images and Videos fail to send. Have only tested with single contact as I don't have a community group. Has been happing since this morning

**Comment by fracting** [comment] 2023-04-02 11:01
Thanks for report @dmastrorillo!

I can reproduce with Session Desktop as well.

It seems the upload file server ( http://filev2.getsession.org ) is down at the moment.

**Comment by KeeJef** [comment] 2023-04-02 11:41
Looking into this now

**Comment by KeeJef** [comment] 2023-04-03 01:15
Users should be able to send files in 1-1 and closed groups again, the Session file server ran out of space due to a large increase in file uploads. Last time this occurred there was a bug in the iOS client which was causing files to be re-uploaded erroneously. We are investigating client implementations now

**Comment by mpretty-cyro** [comment] 2023-04-13 02:20
I uncovered an issue where attachments could be uploaded multiple times due to how the `JobRunner` dependencies were working - I included a fix for this in #823 which is included in version `2.2.12` which will hopefully prevent iOS from causing this again in the future

**Closed** 2024-04-08 23:21 UTC
Labels: bug
