### ISSUE TITLE
Currently no option to select multiple messages

### ISSUE THREAD

**Issue by gitbq** [oxen-io/session-ios#728] opened 2022-10-27 08:26 UTC
**Code of conduct**

- [X ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Long press on messages no longer gives the option to select multiple mesages.
Preiously this option existed.

**To reproduce**

- long press on any message, the menu does not  have any "select" option.
- Android still has the "select" option.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: iphone se 2
 - OS: ios 16.1
 - Version of Session or latest commit hash 2.2.1 (385)

**Additional context**

**Comment by KeeJef** [comment] 2022-12-14 07:09
Closing as duplicate of #468

**Closed by KeeJef** 2022-12-14 07:09 UTC
Labels: feature-request
