### ISSUE TITLE
Creating a Closed Group Session does not include all members selected

### ISSUE THREAD

**Issue by dmoser71** [oxen-io/session-ios#334] opened 2021-01-16 17:41 UTC
**Describe the bug**

When creating a new closed group session for myself and two other users results in only one of the other user's Session App receiving the group connection. My device and the other joined device shows all members as part of the group, but there is always one session that doesn't join upon initial creation. It is random which one doesn't get joined properly.

**To reproduce**

Click on +, then Closed Group icon, select two other people. In my case, I only have three total identities established (myself, plus two others). I select all two available sessions to add to the Closed Group and specify a name for the Closed Group. I tap on Done. Then, only one of the two other devices will show/participate in the Closed Group. 

**Screenshots or logs**

N/A

**Smartphone (please complete the following information):**

 - Device: iPhone 8+ (other devices are iPhone 8+, iPad Air 2)
 - OS: 14.3
 - Version of Session or latest commit hash: 1.7.3 (158)

**Additional context**

There is a workaround possible for this bug. If you remove the (orphaned) person from the Closed Group settings, and then re-add them again to the Closed Group, their device will then join the Closed Group and be able to participate.

**Comment by KeeJef** [comment] 2021-01-17 23:56
We are aware of this issue and should be rolling out a fix ~tomorrow, this fix will overhaul closed groups, and should address this issue

**Comment by dmoser71** [comment] 2021-01-18 00:42
Excellent news! Thank you.

**Comment by sidneyarcidiacono** [comment] 2021-03-29 21:42
I am actually encountering a quite similar issue, although it appears none of our members can correctly access the group. The same **reproduce** steps as @dmoser71 (OP) apply.

I have had this issue since prior to the latest update 1.9.2, and it seems to be persisting. 

Is it more beneficial to continue this thread or would it be preferred I submit a new issue, (as this one indicates a fix but is not yet closed or resolved)?

**Comment by nielsandriesse** [comment] 2021-05-25 04:33
This issue should be fixed on the latest versions of Session.

**Closed by nielsandriesse** 2021-05-25 04:33 UTC
Labels: bug
