### ISSUE TITLE
Missing Button if i add a Session ID User iPhone 14Pro

### ISSUE THREAD

**Issue by Cobramk81** [oxen-io/session-ios#872] opened 2023-07-24 01:31 UTC
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If i want to add a session id to start a new chat i can't see any next button after adding the ID

I can enter the id und unter the fielt there is my own id including qr code but nu discribed next button

I Use an iphone 14 Pro and run the app in german

### Steps To Reproduce

I Phone 14 Pro
Pressing Plus Button
New Session
No Next Button

### iOS Version

IOS 17

### Session Version

2.3.1

**Comment by KeeJef** [comment] 2023-07-24 03:50
Can you share a screenshot of the screen where you expect a next button?

**Comment by Cobramk81** [comment] 2023-07-24 05:10
Yes here

[image0.jpeg]
As you can see no next button on the screen


Von meinem iPhone gesendet

Am 24.07.2023 um 05:50 schrieb Kee Jefferys ***@***.***>:

﻿

Can you share a screenshot of the screen where you expect a next button?

**Comment by KeeJef** [comment] 2023-07-24 05:19
Sorry that attachment did not attach on Github so i can't see it, could you try uploading that screenshot from the GitHub interface?

**Comment by Cobramk81** [comment] 2023-07-24 17:22
![1822](https://github.com/oxen-io/session-ios/assets/74960415/b0589b55-3ad5-4e45-a476-a7f3cb549080)

here is the screenshot

**Comment by KeeJef** [comment] 2023-07-25 00:52
So when you tap inside the "Enter Session ID or ONS name" field a next button is not shown in the center of the screen, or under the keyboard?

**Comment by Cobramk81** [comment] 2023-07-25 02:39
No there is no button shown only the field for the id, the keyboard and the rest is black

Von meinem iPhone gesendet

Am 25.07.2023 um 02:53 schrieb Kee Jefferys ***@***.***>:

﻿

So when you tap inside the "Enter Session ID or ONS name" field a next button is not shown in the center of the screen, or under the keyboard?

**Comment by adorsett** [comment] 2023-07-25 11:31
I can confirm exact same behavior on iPhone 13 Pro Max with latest iOS 17 Dev Beta.

**Comment by mpretty-cyro** [comment] 2023-07-26 07:29
I've just tried to debug this but unfortunately it looks like the latest XCode beta is having some issues with basic thread functions and just hangs indefinitely on launch - unfortunately we are going to have to wait until Apple release an updated version of the XCode beta which will hopefully fix the issue before we can debug 😕

**Comment by mpretty-cyro** [comment] 2023-10-02 03:35
@Cobramk81 or @adorsett are either of you experiencing this in the release version of iOS 17? I haven't found a way to reproduce it with my testing

**Comment by mpretty-cyro** [comment] 2024-04-08 22:43
Closing this as we are unable to reproduce and neither participant has confirmed the issue still exists

**Closed by mpretty-cyro** 2024-04-08 22:43 UTC
Labels: bug
