### ISSUE TITLE
[BUG] No option to delete messages on IOS.

### ISSUE THREAD

**Issue by Bigbrother84844** [oxen-io/session-ios#755] opened 2022-12-15 11:28 UTC
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can delete messages on the Session desktop, but not on IOS. I long press the message but there is no delete option on IOS, Just reply and copy.
![session-attachment-2022-12-15-174334](https://user-images.githubusercontent.com/120645163/207847862-7a47d0e0-504d-49d1-a869-c27bc8edd9cf.jpeg)

### Expected Behavior

I hope the developers will fix this issue soon.

### iOS Version

ios 16.2

### Session Version

2.2.4

### Anything else?

![session-attachment-2022-12-15-174334](https://user-images.githubusercontent.com/120645163/207847946-6e8f7a0f-cf14-459a-8ba6-73290a9eac92.jpeg)

**Comment by RyanRory** [comment] 2023-01-12 00:28
Hi @Bigbrother84844, thanks for the report. Is it happening in community chats, groups chats, or 1-1 chats? Did you send the message in the screenshot from desktop and the iOS is a linked device?

**Comment by fracting** [comment] 2023-01-30 00:05
I can reproduce this bug with Session iOS 2.2.4 and 2.2.5.

I believe it is Community only. Deletion works fine with closed group / 1-1 DM chat.

I suspect it has the same root cause as https://github.com/oxen-io/session-ios/issues/768 where there's some mismatching (or missing value) of one's own blinded ID / one's own unblinded ID which triggers an incorrect conditional branch that does not render the deletion button.

**Comment by GittyUpMyHorsey** [comment] 2023-02-04 23:48
I can also reproduce this on the latest ios version with the latest  session version.

Delete appears in 1 to 1 and group chats just not community chats.

**Comment by RyanRory** [comment] 2023-02-07 23:23
Hi guys, this issue should be fixed in our latest release 2.2.6. Thanks for helping us debug this issue. I'll close this issue now.

**Comment by fracting** [comment] 2023-02-08 00:10
Thanks for the fix!

I retested this one with 2.2.6, new message sent to Community can be deleted, old message that existed before the new release can not be deleted, I guess there's nothing we can do with the old message? If that's the case I'm fine, just report my findings.

**Comment by fracting** [comment] 2023-02-08 02:12
Actually what's interesting:

* In Community
  * After applying the fix (upgrade to 2.2.6)
    * If the original message was sent from iOS, then I can delete it from iOS
    * If the original message was sent from Desktop, then I can't delete it from iOS

It seems like we have a lot of combinations to test, like the ones in https://github.com/oxen-io/session-desktop/issues/2655#issuecomment-1401403829

@RyanRory should we reopen this issue?

**Comment by mpretty-cyro** [comment] 2023-02-09 23:18
Hmm - yep will reopen

**Comment by mpretty-cyro** [comment] 2023-02-10 01:06
> * If the original message was sent from Desktop, then I can't delete it from iOS

🤦 forgot about ID Blinding - I'll open a PR for this now

**Comment by fracting** [comment] 2023-03-16 02:05
This one is fixed for me in Session iOS 2.2.8

**Comment by mpretty-cyro** [comment] 2023-03-16 02:39
Fixed in #795

**Closed by mpretty-cyro** 2023-03-16 02:39 UTC
Labels: bug
