### ISSUE TITLE
Conversation view is not immediately updated upon notification

### ISSUE THREAD

**Issue by trosel** [oxen-io/session-ios#632] opened 2022-06-02 20:20 UTC
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Get a notification for a new message. Convo does not yet have the new message in it. New message appears when you back out to convo list view.

The flow goes like this:

* Get Push Notification
* Click it
* Sent to Conversation view
* No new message
* Went back to threads view
* Saw new message in Conversation
* Go back into Conversation view and it was there

**To reproduce**

* Use fast mode notifications
* **Have Background Refresh turned off in the system settings**

**Smartphone (please complete the following information):**

 - Device: iPhone 11 pro max
 - OS: iOS 15.4.1
 - Version of Session or latest commit hash: v1.12.9

**Additional context**

* It's possible that having background refresh turned off is causing some strange behavior.

* Ideally, the app should inject the message into the conversation based on the push

* Other messaging apps don't have this issue even when Background Refresh is disabled on them as well.

**Comment by RyanRory** [comment] 2022-06-29 23:31
Hi @trosel, thanks for the report! We have been aware of this issue and we are working on it. Will keep you updated once the issue is fixed.

Cheers!

**Comment by RyanRory** [comment] 2022-12-14 23:17
Hi @trosel, this issue should be fixed a couple of releases ago. I'll close this issue for now. If you still see this happens, we'll reopen this issue and dig into it deeper. Thanks!

**Closed by RyanRory** 2022-12-14 23:17 UTC
Labels: bug
